### PR TITLE
feat: Added forgot password feature

### PR DESCRIPTION
**Pull request by hemanth110702**
# Description
#4 - Add forgot password feature

# Solution
- Added forgot password button in login page
- Added a web page to reset password
- With these enhancement user can reset their password if they forgot

### CODE REVIEW

**Comment by thakurthegr8** [comment]
Please share a short video of the issue you have resolved @hemanth110702

**Review by thakurthegr8 — CHANGES_REQUESTED** [review]
Please look into issues

**Comment by hemanth110702** [comment]
# Demo video

https://github.com/thakurthegr8/loop/assets/89832451/2fb37871-ec6b-43c6-9df5-8a0eb85e318b

**Comment by thakurthegr8** [comment]
> # Demo video
>  loop.-.demo.video.mp4

Great @hemanth110702 I've added some issues regarding code practices please fix them.

**Comment by hemanth110702** [comment]
- I have resolved the issues.
- Here is the video after changes done.
# Demo Video
[loop - added sx component.webm](https://github.com/thakurthegr8/loop/assets/89832451/30d1ef30-a2c1-41f5-8cb5-0fc28766d71b)

**Comment by thakurthegr8** [comment]
Great @hemanth110702  I have merged your PR.

**Pull request merged**
